options:
  repo:
    type: string
    default: "default-repo"
    description: "The git repository from which to check out"
  commit-or-branch:
    type: string
    default: "default-commit"
    description: "The git branch or commit to check out"
  debug:
    type: bool
    default: false
    description: "Whether to run the site in debug mode"
  install_sources:
    type: string
    default: |
      - ppa:yellow/ppa
    description: (READ ONLY) apt source list line from where to get bundleservices deb.
  install_keys:
    type: string
    default: |
      - null
    description: (READ ONLY) List of keys to accept (none required for PPAs)
  extra_packages:
    type: string
    default: ''
    description: A space separated list of additional deb packages to install on each unit.
  requirements_file:
    type: string
    default: 'requirements.txt'
    description: Pip requirements file for additional packages.
