options:
  repo:
    type: string
    default: "default-repo"
    description: "The git repository from which to check out"
  commit-or-branch:
    type: string
    default: "default-commit"
    description: "The git branch or commit to check out"
  port:
    type: int
    default: 8000
    description: "The port on which to serve"

